name: Build Docker

on:
  - push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: cwfitzgerald/bve-dev-env
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
